`cloud_storage`: deflake `test_remote_partition_read_cached_index`
This can flake depending on timing, if we hit the deadline before consuming
the second batch:

```
DEBUG 2026-01-21 03:15:28,587 [shard 0:main] cloud_storage - [fiber719 kafka/test-topic/42] - remote_partition.cc:384 - We're over-budget, stopping, config: start_offset:5, max_offset:44, min_bytes:0, max_bytes:4096, strict_max_bytes:false, type_filter: {nullopt}, first_timestamp:{nullopt}, bytes_consumed:1779, over_budget:false, abortable:false, client_address:{nullopt}, deadline exceeded.
src/v/cloud_storage/tests/remote_partition_test.cc(1119): fatal error: in "test_remote_partition_read_cached_index": critical check headers_read.size() == 2 has failed [1 != 2]
```

Change the condition to expect more than 0 batches consumed instead of two.