rptest: ignore sync errors when resetting manifest
Sync errors may happen for a variety of reasons, but generally they are
transient. This was causing the test to fail:

```
[WARNING - 2025-10-08 10:01:40,588 - admin - _request - lineno:805]: Response 500: {"message": "Could not sync with log", "code": 500}
[INFO  - 2025-10-08 10:01:40,588 - e2e_shadow_indexing_test - test_reset_from_cloud - lineno:524]: Reset from cloud failed: 500 Server Error: Internal Server Error for url: http://docker-rp-6:9644/v1/cloud_storage/unsafe_reset_metadata_from_cloud/kafka/panda-topic/0
[DEBUG - 2025-10-08 10:01:43,407 - kgo_verifier_services - _ingest_status - lineno:433]: KgoVerifierProducer-0-139894623949760 status: [{'topic': 'panda-topic', 'sent': 89864, 'acked': 88839, 'bad_offsets': 0, 'max_offsets_produced': {'0': 88838}, 'restarts': 0, 'fails': 0, 'tombstones_produced': 0, 'failed_transactions': 0, 'aborted_transaction_msgs': 0, 'latency': {'p50': 13798.5, 'p90': 21826, 'p99': 370127}, 'active': True}]
...
[ERROR - 2025-10-08 10:02:05,643 - cluster - _do_post_test_checks - lineno:136]: Test failed, doing failure checks on RedpandaService-0-139894623572640...
Traceback (most recent call last):
  File "/root/tests/rptest/services/cluster.py", line 246, in wrapped
    r = f(self, *args, **kwargs)
  File "/root/tests/rptest/tests/e2e_shadow_indexing_test.py", line 537, in test_reset_from_cloud
    assert resets_failed == 0, f"{resets_failed} resets failed during the test"
AssertionError: 1 resets failed during the test
```