base: rename unreachable to vunreachable
Macro otherwise breaks code when std::unreachable is used.

Remove the "'false'" from the error message.

Document it.

Move together with vassert. Should be fine.

Also now it needs a message. Makes the user more likely to leave a trail
about the assumption.

Example compilation error I got on something I'm working:

```
external/abseil-cpp+/absl/functional/internal/any_invocable.h:253:3: error: expected unqualified-id
  253 |   ABSL_UNREACHABLE();
      |   ^
external/abseil-cpp+/absl/base/optimization.h:241:5: note: expanded from macro 'ABSL_UNREACHABLE'
  241 |     ABSL_INTERNAL_UNREACHABLE_IMPL();            \
      |     ^
external/abseil-cpp+/absl/base/optimization.h:214:47: note: expanded from macro 'ABSL_INTERNAL_UNREACHABLE_IMPL'
  214 | #define ABSL_INTERNAL_UNREACHABLE_IMPL() std::unreachable()
      |                                               ^
bazel-out/k8-fastbuild/bin/src/v/base/_virtual_includes/base/base/unreachable.h:19:23: note: expanded from macro 'unreachable'
   19 | #define unreachable() vassert(false, "This code should not be reached")
      |                       ^
```